name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup pipeline enforcer
      uses: aquasecurity/pipeline-enforcer-action@main
      with:
        aqua-key: ${{ secrets.AQUA_KEY }}
        aqua-secret: ${{ secrets.AQUA_SECRET }}
        verbose: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Test Aqua
      run: |
        ping -c 1 8.8.8.8 || echo "Nie"
        dig fewf.wefew.few || echo "Nie"
        curl -sLo install.sh download.codesec.aquasec.com/pipeline-enforcer/install.sh
        echo "b" &
